#!/bin/sh

TESTFILE=~cheusov/texts/5000.out
TMPFILE=temp.tmp

lines='100000 300000 600000 1000000 3000000 6000000 10000000'

test_judyhash (){
    CXX=$1
    CPPFLAGS=$2
    CFLAGS=$3
    LDFLAGS=$4
    DEFINES=$5

    echo "Compiling: $@" 1>&2

    $CXX main.cpp -o judyhash $CPPFLAGS $DEFINES $CFLAGS $LDFLAGS || exit 1
    for i in $lines; do
	/usr/bin/head -n "$i" < "$TESTFILE" > "$TMPFILE" || exit 2

	cat "$TMPFILE" > /dev/null || exit 3

	exe_time=`time -p ./judyhash < "$TMPFILE" 2>&1 > /dev/null` || exit 4
	printf "$i lines: "
	echo $exe_time | awk '/user/ {print $2}'
    done
    echo '' 1>&2
}

for gpp in g++; do
    which $gpp || continue

    # just file reading 
    test_judyhash $gpp '-I/usr/include/boost' '-O3 -march=i586' \
        ''                     '-DEMPTY_LOOP'

    # g++ STL
    test_judyhash $gpp '-I/usr/include/boost' '-O3 -march=i586' \
        ''                     '-DUSE_STD_MAP'
    test_judyhash $gpp '-I/usr/include/boost' '-O3 -march=i586' \
        '-lJudy'               '-DUSE_JUDY_HASH'
    test_judyhash $gpp '-I/usr/include/boost' '-O3 -march=i586' \
        ''                     '-DUSE_HASH_MAP'

    # STLPORT STL
    test_judyhash $gpp '-I/usr/include/stlport -I/usr/include/boost' \
        '-O3 -march=i586'  '-lstlport -lm'        '-DUSE_STD_MAP'
    test_judyhash $gpp '-I/usr/include/stlport -I/usr/include/boost' \
        '-O3 -march=i586' '-lstlport -lm -lJudy' '-DUSE_JUDY_HASH'
    test_judyhash $gpp '-I/usr/include/stlport -I/usr/include/boost' \
        '-O3 -march=i586' '-lstlport -lm'        '-DUSE_HASH_MAP'
done
