##### Compiler
CXX=c++
#CXX=icc
#CXX=g++

##### preprocessor flags
CPPFLAGS_COMMON=-I/usr/pkg/include
#CPPFLAGS_SPARSEHASH=
CPPFLAGS_BOOST=-I/usr/pkg/include/boost
#CPPFLAGS_STLPORT=-I/usr/pkg/include/stlport

##### compilation flags
CFLAGS_COMMON=
CFLAGS_OPT=-O3 -DNDEBUG
CFLAGS_TEST=-O0 -g

##### linking flags
LDFLAGS_COMMON=-L/usr/pkg/lib
LDFLAGS_STLPORT=-lstlport_gcc
LDFLAGS_JUDY=-lJudy
LDFLAGS_TEST=-g
