#!/bin/sh

##### bench options
ITEMS='50000 500000 5000000'
TYPES='sparse dense judy_l judy_m judy_kd hash map'

gmake time_hash_map || exit 2

for n in $ITEMS; do
    for t in $TYPES; do
	./time_hash_map -t $t -n $n
    done
done
