#!/bin/sh

#
# usage: tables2plot <bench_type> <test_type> [files...]
#

bench_type=$1
shift

test_type=$1
shift

if test -r bench_${bench_type}_template_$test_type.gnuplot; then
    cat bench_${bench_type}_template_$test_type.gnuplot
else
    cat bench_${bench_type}_template.gnuplot
fi

printf "plot "

cnt=0
for i; do
    j=`echo ${i} | sed -e 's/^bench_'"$bench_type"'_//' -e 's/_[^_]*[.]tmp$//'`
    test $cnt = 0 || printf ,
    printf "%s" " \"${i}\" title \"${j}\" with linespoints"
    cnt=$(($cnt+1))
done
printf '\n'
