#!/bin/sh

#
# usage: bench2table_mask <map_type> <test_type> <mask> [files...]
#

map_type="$1"
shift

test_type="$1"
shift

mask="$1"
shift

awk -v map_type="$map_type" -v test_type="$test_type" -v mask="$mask" '
BEGIN {
   skip = 0
}

NF == 0 {
   skip = 0
   next
}

skip != 0 {
   next
}

$4 == "iterations" {
   if (map_type != $1 || mask != $11){
      skip=1
      next
   }

   iters = $3
   next
}

$1 == test_type {
   print iters, $2
}
' "$@"
