INCS= \
   judy_map.h judy_map_kdcell.h judy_map_l.h judy_map_m.h \
   judy_map_vcell.h judy_set.h judy_set_cell.h judy_set_l.h judy_set_m.h \
   judyarray/judy_common.h judyarray/judy_map_common.h \
   judyarray/judy_mapset_common.h judyarray/judy_mapset_list.h \
   judyarray/judy_mapset_map.h judyarray/judy_set_common.h

#judyarray/judy_mapset_vcell_common.h

.include <mkc.files.mk>
